name = "QuartzGetWindow"
uuid = "17db2c3b-b50d-4e4f-b335-13ed37e59eac"
authors = ["SatoshiTerasaki <terasakisatoshi.math@gmail.com>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
ObjectiveC = "e86c9b32-1129-44ac-8ea0-90d5bb39ded9"

[compat]
Aqua = "0.8.9"
JET = "0.9.12"
Libdl = "1"
ObjectiveC = "3"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
